### ISSUE TITLE
USA Mirror returns 404

### ISSUE THREAD

**Issue by EigenDev** [arch4edu/arch4edu#175]
Hello, 

Firstly, thank you verry much for the availability of this repo.
Problem --- running `pacman -Syu`  returns to following:
`:: Synchronizing package databases...
 arch4edu.db failed to download
error: failed retrieving file 'arch4edu.db' from arch4edu.keybase.pub : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
`
It seems the USA mirror is broken or has been moved?

**Comment by petronny** [comment]
Yeah the keybase account of arch4edu is recently reset and previous files are also lost in the reset.
I tried a sync a few days ago but some files are still broken. I'll try another sync tomorrow.

**Comment by amralmorsi** [comment]
Still have same issue here

**Comment by petronny** [comment]
Hi, the sync process has been started yesterday and it seems to be correct.

But re-uploading all files for the first time will take a few days. Currently it's updating the `x86_64` folder and the `aarch64` and `any` folders have been updated now.

**Comment by petronny** [comment]
The sync process has finished.

**Comment by sudokit** [comment]
I am still experiencing this issue.

`:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 arch4edu.db failed to download
error: failed retrieving file 'arch4edu.db' from arch4edu.keybase.pub : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)`

**Comment by amralmorsi** [comment]
Yep same here. The US mirror still returns 404 error for me.

**Comment by petronny** [comment]
seems that keybase.pub still has trouble with symbolic links. I'll replace the links with copies tomorrow.

**Comment by petronny** [comment]
```
$ curl -O https://arch4edu.keybase.pub/x86_64/arch4edu.db
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  671k  100  671k    0     0   138k      0  0:00:04  0:00:04 --:--:--  155k
```
Should be solved now.

**Comment by sudokit** [comment]
I am still getting this error with certain packages on other servers. Like trying to install:
`paru -S hip-runtime-amd                                                                                                                                                                                     (base) 
:: hip-runtime-amd is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n] y
resolving dependencies...
looking for conflicting packages...

Packages (1) hip-runtime-amd-5.2.3-1

Total Download Size:    5.51 MiB
Total Installed Size:  16.69 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 hip-runtime-amd-5.2.3-1-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'hip-runtime-amd-5.2.3-1-x86_64.pkg.tar.zst' from pkg.fef.moe : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.`

**Comment by petronny** [comment]
@sudokit Oh, that package must be accidentally removed when implementing https://github.com/arch4edu/cactus/issues/2 .
I believe a rebuild would fix such kind of error.

If you find more packages that return 404, please report it here or to the telegram group.

**Comment by Mhowser** [comment]
Still having issues downloading packages from the US mirror:

```
$ yay -S rocm-hip-sdk rocm-opencl-sdk
resolving dependencies...
looking for conflicting packages...

Packages (36) comgr-5.2.3-1  hip-runtime-amd-5.2.3-1  hipblas-5.2.3-1  hipcub-5.2.3-1  hipfft-5.2.3-1  hipsolver-5.2.1-1  hipsparse-5.2.3-1
              hsa-amd-aqlprofile-bin-5.2.3-1  hsa-rocr-5.2.3-1  hsakmt-roct-5.2.3-1  miopen-hip-5.2.3-1  openmp-14.0.6-1  rccl-5.2.3-1  rocalution-5.2.3-1
              rocblas-5.2.3-1  rocfft-5.2.3-1  rocm-clang-ocl-5.2.3-1  rocm-cmake-5.2.3-1  rocm-core-5.2.1-2  rocm-device-libs-5.2.3-1
              rocm-hip-libraries-5.2.1-2  rocm-hip-runtime-5.2.1-1  rocm-language-runtime-5.2.1-1  rocm-llvm-5.2.3-1  rocm-llvm-mlir-5.3.0-1
              rocm-opencl-runtime-5.2.3-1  rocm-smi-lib-5.2.3-1  rocminfo-5.2.3-1  rocprim-5.2.3-1  rocrand-5.2.3-1  rocsolver-5.2.3-1  rocsparse-5.2.3-1
              rocthrust-5.2.3-1  z3-4.11.0-1  rocm-hip-sdk-5.2.1-2  rocm-opencl-sdk-5.2.1-1

Total Download Size:    912.37 MiB
Total Installed Size:  9564.42 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 rocm-llvm-5.2.3-1-x86_64.pkg.tar.zst failed to download
 rocblas-5.2.3-1-x86_64                                             46.4 MiB  1045 KiB/s 00:45 [########################################################] 100%
 rocm-llvm-mlir-5.3.0-1-x86_64                                      78.6 MiB  1107 KiB/s 01:13 [########################################################] 100%
 miopen-hip-5.2.3-1-x86_64.pkg.tar.zst failed to download
 rocfft-5.2.3-1-x86_64                                              99.6 MiB  1191 KiB/s 01:26 [########################################################] 100%
 Total ( 5/36)                                                     912.4 MiB  10.6 MiB/s 01:26 [########################################################] 100%
error: failed retrieving file 'rocm-llvm-5.2.3-1-x86_64.pkg.tar.zst' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'miopen-hip-5.2.3-1-x86_64.pkg.tar.zst' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
```

**Comment by petronny** [comment]
```
$ curl -O https://arch4edu.keybase.pub/x86_64/miopen-hip-5.2.3-1-x86_64.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65.3M  100 65.3M    0     0   716k      0  0:01:33  0:01:33 --:--:--  723k

$ curl -O https://arch4edu.keybase.pub/x86_64/rocm-llvm-5.2.3-1-x86_64.pkg.tar.zst                                                                                                                                                                                                                                                                                                                           
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  495M  100  495M    0     0   837k      0  0:10:05  0:10:05 --:--:-- 1029k
```

@Mhowser Please try downloading them again.

**Comment by Mhowser** [comment]
Everything downloads successfully this time except `rocm-llvm-5.2.3-1-x86_64.pkg.tar.zst`, I keep getting `Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds` with this package and it never downloads it.

**Comment by petronny** [comment]
> Is it possible to tell yay to use this package I manually downloaded instead?

Then `yay -U rocm-llvm-5.2.3-1-x86_64.pkg.tar.zst`

**Comment by Mhowser** [comment]
Ah of course! Thank you! Not sure why this particular package takes so long to retrieve, but everything works now.

**Comment by petronny** [comment]
We also proposed [a mirror request to xtom.com](https://github.com/xtomcom/mirrorrequest/issues/13). Please vote for it if you want to have a mirror of arch4edu at:
- San Jose, CA
- Amsterdam, NL
- Düsseldorf, Germany
- Tallinn, Estonia
- Osaka, Japan
- Sydney, Australia

**Comment by carlosal1015** [comment]
Voted, I love the repository.

**Comment by billop** [comment]
There are still some issues with some packages.
```
:: Retrieving packages...
 rocminfo-5.3.0-1-x86_64                                27.7 KiB  11.1 KiB/s 00:02 [################################################] 100%
 rocm-language-runtime-5.2.3-1-x86_64                    2.2 KiB   493   B/s 00:05 [################################################] 100%
 hsa-rocr-5.3.0-1-x86_64.pkg.tar.zst failed to download
 comgr-5.3.0-1-x86_64.pkg.tar.zst failed to download
 rocm-hip-runtime-5.3.0-1-x86_64.pkg.tar.zst failed to download
 hip-runtime-amd-5.3.0-1-x86_64                          5.7 MiB   195 KiB/s 00:30 [################################################] 100%
 Total (6/6)                                            40.8 MiB  1251 KiB/s 00:33 [################################################] 100%
error: failed retrieving file 'comgr-5.3.0-1-x86_64.pkg.tar.zst' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'hsa-rocr-5.3.0-1-x86_64.pkg.tar.zst' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'rocm-hip-runtime-5.3.0-1-x86_64.pkg.tar.zst' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: too many errors from arch4edu.keybase.pub, skipping for the remainder of this transaction
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
 ```

**Comment by petronny** [comment]
Maybe the keybase mirror doesn't work well with parallel downloading. How about disabling it?

**Comment by Mhowser** [comment]
It appears that the mirror is down again.
```
$ paru -Sy
[sudo] password for deck: 
:: Synchronizing package databases...
 jupiter-rel is up to date
 holo-rel is up to date
 core-rel is up to date
 extra-rel is up to date
 community-rel is up to date
 multilib-rel is up to date
 arch4edu.db failed to download
error: failed retrieving file 'arch4edu.db' from arch4edu.keybase.pub : Could not resolve host: arch4edu.keybase.pub
warning: too many errors from arch4edu.keybase.pub, skipping for the remainder of this transaction
error: failed to synchronize all databases (invalid url for server)
```

**Comment by petronny** [comment]
https://github.com/arch4edu/mirrorlist/issues/6

**Comment by Mhowser** [comment]
> We also proposed [a mirror request to xtom.com](https://github.com/xtomcom/mirrorrequest/issues/13). Please vote for it if you want to have a mirror of arch4edu at:
> 
> * San Jose, CA
> * Amsterdam, NL
> * Düsseldorf, Germany
> * Tallinn, Estonia
> * Osaka, Japan
> * Sydney, Australia

Can we revisit this possible solution for US mirrors?

**Comment by petronny** [comment]
> Can we revisit this possible solution for US mirrors?

Well. If there's no response from xtom then we can do nothing about it either.

For now it may be possible to use kbfs to directly access the repository shared on keybase. They are still synchronized.

I'll also do some research on p2p file transfer.

**Comment by petronny** [comment]
> For now it may be possible to use kbfs to directly access the repository at keybase://public/arch4edu . They are still synchronized.

The keybase mirror is officially shut down. Also we are testing a new global mirror at https://repository.arch4edu.org.
